export const TERMS_SECTIONS = [
  {
    id: 'acceptance',
    title: 'Acceptance of Terms',
    content: [
      {
        text: 'By accessing and using FlashFusion ("Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.'
      },
      {
        text: 'These Terms of Service ("Terms") govern your use of our website located at flashfusion.dev (the "Service") operated by FlashFusion Inc. ("us", "we", or "our").'
      }
    ]
  },
  {
    id: 'description',
    title: 'Description of Service',
    content: [
      {
        text: 'FlashFusion is an AI-powered platform that provides web application development tools, including but not limited to code generation, deployment automation, project templates, and collaboration features.'
      },
      {
        text: 'The Service includes both free and paid features. Paid features require a valid subscription and are subject to additional terms outlined in your subscription agreement.'
      }
    ]
  },
  {
    id: 'user-accounts',
    title: 'User Accounts',
    content: [
      {
        subtitle: 'Account Creation',
        text: 'To access certain features of the Service, you must register for an account. You agree to provide accurate, current, and complete information during the registration process.'
      },
      {
        subtitle: 'Account Security',
        text: 'You are responsible for safeguarding the password and all activities that occur under your account. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.'
      },
      {
        subtitle: 'Account Termination',
        text: 'We reserve the right to terminate or suspend your account at any time for violation of these Terms or for any other reason we deem necessary.'
      }
    ]
  },
  {
    id: 'acceptable-use',
    title: 'Acceptable Use Policy',
    content: [
      {
        subtitle: 'Prohibited Activities',
        text: 'You agree not to use the Service for any unlawful purpose or in any way that could damage, disable, overburden, or impair the Service.'
      },
      {
        subtitle: 'Content Restrictions',
        text: 'You may not use the Service to generate, store, or distribute content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable.'
      },
      {
        subtitle: 'System Integrity',
        text: 'You may not attempt to gain unauthorized access to any part of the Service, other accounts, or computer systems connected to the Service.'
      }
    ]
  },
  {
    id: 'intellectual-property',
    title: 'Intellectual Property Rights',
    content: [
      {
        subtitle: 'Your Content',
        text: 'You retain ownership of all code, projects, and content you create using our Service. We do not claim ownership of your intellectual property.'
      },
      {
        subtitle: 'Our Service',
        text: 'The Service and its original content, features, and functionality are and will remain the exclusive property of FlashFusion Inc. and its licensors.'
      },
      {
        subtitle: 'Generated Code',
        text: 'Code generated by our AI tools is provided to you under a permissive license. You may use, modify, and distribute such code without attribution, subject to applicable laws.'
      }
    ]
  },
  {
    id: 'payment-terms',
    title: 'Payment and Billing',
    content: [
      {
        subtitle: 'Subscription Fees',
        text: 'Paid plans are billed in advance on a monthly or yearly basis. All fees are non-refundable except as required by law or as specified in our refund policy.'
      },
      {
        subtitle: 'Auto-Renewal',
        text: 'Your subscription will automatically renew at the end of each billing period unless you cancel before the renewal date.'
      },
      {
        subtitle: 'Price Changes',
        text: 'We reserve the right to modify our pricing with 30 days advance notice. Changes will take effect at your next billing cycle.'
      }
    ]
  },
  {
    id: 'privacy',
    title: 'Privacy and Data Protection',
    content: [
      {
        text: 'Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your information when you use our Service.'
      },
      {
        text: 'By using our Service, you agree to the collection and use of information in accordance with our Privacy Policy.'
      }
    ]
  },
  {
    id: 'disclaimers',
    title: 'Disclaimers and Limitation of Liability',
    content: [
      {
        subtitle: 'Service Availability',
        text: 'We strive to provide reliable service but cannot guarantee 100% uptime. The Service is provided "as is" without warranties of any kind.'
      },
      {
        subtitle: 'Limitation of Liability',
        text: 'In no event shall FlashFusion Inc. be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.'
      },
      {
        subtitle: 'Maximum Liability',
        text: 'Our total liability to you for any damages shall not exceed the amount you paid us in the 12 months preceding the claim.'
      }
    ]
  },
  {
    id: 'termination',
    title: 'Termination',
    content: [
      {
        subtitle: 'Termination by You',
        text: 'You may terminate your account at any time by contacting our support team or using the account deletion feature in your settings.'
      },
      {
        subtitle: 'Termination by Us',
        text: 'We may terminate or suspend your access immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users.'
      },
      {
        subtitle: 'Effect of Termination',
        text: 'Upon termination, your right to use the Service will cease immediately. All provisions that should survive termination shall survive.'
      }
    ]
  },
  {
    id: 'changes',
    title: 'Changes to Terms',
    content: [
      {
        text: 'We reserve the right to modify these Terms at any time. We will notify users of significant changes via email or through the Service.'
      },
      {
        text: 'Your continued use of the Service after changes constitutes acceptance of the new Terms.'
      }
    ]
  },
  {
    id: 'contact',
    title: 'Contact Information',
    content: [
      {
        text: 'If you have any questions about these Terms, please contact us at legal@flashfusion.dev or through our contact page.'
      }
    ]
  }
] as const;

export const LIABILITY_TABLE = [
  {
    type: 'Direct Damages',
    coverage: 'Limited to subscription fees paid',
    period: 'Last 12 months'
  },
  {
    type: 'Data Loss',
    coverage: 'Best effort recovery only',
    period: 'No monetary liability'
  },
  {
    type: 'Service Interruption',
    coverage: 'Service credits may apply',
    period: 'Per SLA terms'
  },
  {
    type: 'Third-party Claims',
    coverage: 'Indemnification provided',
    period: 'Subject to cooperation'
  }
] as const;

export const GOVERNING_LAW = {
  jurisdiction: 'State of California, USA',
  court: 'San Francisco County',
  arbitration: 'Required for disputes under $10,000',
  language: 'English'
} as const;