/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gcqfqzhgludrzkfajljp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjcWZxemhnbHVkcnprZmFqbGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjQ1OTAsImV4cCI6MjA2OTAwMDU5MH0.N2F1BZq7ZJig-GSdr2Kv_WkHtWHI5bVS4JaKkc1u-Sk"